feat: add support for other abbreviations and fulln book names

diff --git a/bib b/bib
--- a/bib
+++ b/bib
@@ -11,8 +11,8 @@ show_help() {
   exit 1
 }
 
-# Clear version variable if it exists and set defaults for others
-ARG_CONTEXT="true" # Which version to use from BibleGateway.com
+# clear version variable if it exists and set defaults for others
+ARG_CONTEXT="true" # which version to use from BibleGateway.com
 
 # Process command line args
 while getopts ':c?h' c; do
@@ -28,9 +28,15 @@ main() {
   dir_of_script=$(dirname $(readlink -f $0))
   bible_dir="${dir_of_script}/${bible_name}"
   chapter_file="${bible_dir}/${1}.md"
+  # enter if given book name is an abbreviation
   if [ ! -f "${chapter_file}" ]; then
-    echo "[bib] chapter not found: ${1}"
-    exit 1
+    find_chapter $1
+    chapter_file="${bible_dir}/${book}${chapter}.md"
+    # enter if book name does not exist
+    if [ ! -f "${chapter_file}" ]; then
+      echo "[bib] chapter not found: ${1}"
+      exit 1
+    fi
   fi
   text=$(cat "${chapter_file}")
 
@@ -457,6 +463,85 @@ print_chapter() {
     echo -e "$text"
   )"
   echo "$output" | less -RFX
+}
+
+find_chapter() {
+  books_array='{
+    "genesis": ["gen", "gn", "ge"],
+    "exodus": ["ex", "exod", "exo"],
+    "leviticus": ["lev", "le", "lv"],
+    "numbers": ["num", "nu", "nm", "nb"],
+    "deuteronomy": ["deut", "de", "dt"],
+    "joshua": ["josh", "jos", "jsh"],
+    "judges": ["judg", "jdg", "jg", "jdgs"],
+    "ruth": ["rth", "ru"],
+    "1samuel": ["1sam", "1sm", "1sa", "1s", "isam", "isa", "1samuel", "1sam", "1s", "1stsamuel", "1stsam", "firstsamuel", "firstsam"],
+    "2samuel": ["2sam", "2sm", "2sa", "2s", "iizam", "iisa", "2sam", "2sam", "2s", "2ndsamuel", "2ndsam", "secondsamuel", "secondsam"],
+    "1kings": ["1kgs", "1ki", "1kgs", "1kin", "1ki", "1k", "iikgs", "iiki", "1stkings", "1stkgs", "firstkings", "firstkgs"],
+    "2kings": ["2kgs", "2ki", "2kgs", "2ki", "2k", "iikgs", "2ndkings", "2ndkgs", "seconds", "secondkings", "secondkgs"],
+    "1chronicles": ["1chron", "1chr", "1ch", "1chron", "1chr", "1ch", "iichron", "iichr"],
+    "ezra": ["ezr", "ez"],
+    "nehemiah": ["neh", "ne"],
+    "esther": ["est", "esth", "es"],
+    "job": ["jb"],
+    "psalm": ["ps", "psalms", "pslm", "psa", "psm", "pss"],
+    "proverbs": ["prov", "pro", "prv", "pr"],
+    "ecclesiastes": ["eccles", "eccle", "ecc", "ec", "qoh"],
+    "song": ["songofsolomon", "songofsongs", "sos", "so", "canticleofcanticles", "canticles", "cant"],
+    "isaiah": ["isa", "is"],
+    "jeremiah": ["jer", "je", "jr"],
+    "lamentations": ["lam", "la"],
+    "ezekiel": ["ezek", "eze", "ezk"],
+    "daniel": ["dan", "da", "dn"],
+    "hosea": ["hos", "ho"],
+    "joel": ["jl"],
+    "amos": ["am"],
+    "obadiah": ["obad", "ob"],
+    "jonah": ["jnh", "jon"],
+    "micah": ["mic", "mc"],
+    "nahum": ["nah", "na"],
+    "habakkuk": ["hab", "hb"],
+    "zephaniah": ["zeph", "zep", "zp"],
+    "haggai": ["hag", "hg"],
+    "zechariah": ["zech", "zec", "zc"],
+    "malachi": ["mal", "ml"],
+    "matthew": ["matt", "mt"],
+    "mark": ["mrk", "mar", "mk", "mr"],
+    "luke": ["luk", "lk"],
+    "john": ["joh", "jhn", "jn"],
+    "acts": ["act", "ac"],
+    "romans": ["rom", "ro", "rm"],
+    "1corinthians": ["1cor", "1co", "icor", "ico", "1cor", "1co", "1corinthians", "1stcorinthians", "firstcorinthians"],
+    "2corinthians": ["2cor", "2co", "iicor", "iico", "2cor", "2co", "2corinthians", "2ndcorinthians", "secondcorinthians"],
+    "galatians": ["gal", "ga"],
+    "ephesians": ["eph", "ephes"],
+    "philippians": ["phil", "php", "pp"],
+    "colossians": ["col", "co"],
+    "1thessalonians": ["1thess", "1thes", "1th", "ithessalonians", "ithess", "ithes", "1thessalonians", "1thess", "1stthessalonians"],
+    "2thessalonians": ["2thess", "2thes", "2th", "iithessalonians", "iithess", "iithes", "2thessalonians", "2thess", "2ndthessalonians"],
+    "1timothy": ["1tim", "1ti", "itimothy", "itim", "iti", "1timothy", "1tim", "1sttimothy", "1sttim", "firsttimothy", "firsttim"],
+    "2timothy": ["2tim", "2ti", "iitimothy", "iitim", "iiti", "2timothy", "2tim", "2ndtimothy", "2ndtim", "secondtimothy"],
+    "titus": ["tit", "ti"],
+    "philemon": ["philem", "phm", "pm"],
+    "hebrews": ["heb"],
+    "james": ["jas", "jm"],
+    "1peter": ["1pet", "1pe", "1pt", "1p", "ipet", "ipt", "ipe", "1pet", "1pt", "1p", "1peter"],
+    "2peter": ["2pet", "2pe", "2pt", "2p", "iipet", "iipt", "iipe", "2peter", "2pt", "2peter"],
+    "1john": ["1joh", "1jhn", "1jn", "1j", "1john", "1jhn", "1joh", "1jn", "1jo", "1j", "ijohn"],
+    "2john": ["2joh", "2jhn", "2jn", "2j", "2john", "2jhn", "2joh", "2jn", "2jo", "2j", "iijohn"],
+    "3john": ["3joh", "3jhn", "3jn", "3j", "3john", "3jhn", "3joh", "3jn", "3jo", "3j", "iiijohn"],
+    "jude": ["jud", "jd"],
+    "revelation": ["rev", "re"]
+  }'
+
+  # remove the trailing digits to get the book name
+  book=$(echo "$1" | sed 's/[0-9]*$//')
+
+  # remove the letters to get the chapter number
+  chapter=$(echo "$1" | sed 's/^[0-9]*[a-zA-Z]*//')
+
+  # find book in books array
+  book=$(echo "$books_array" | jq -r --arg book "$book" 'to_entries[] | select(.value[] == $book) | .key')
 }
 
 main "$@"
